services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
    volumes:
      -  /mnt/sdb:/data
    evironment:
      RAM_SIZE: "12"
      CPU_CORES: "4"
      DISK_SIZE: "500G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
