services:
  windows:
    image: dockurr/windows
    container_name: windows
    volumes:
      - /mnt/sdb:/data
    environment:
      VERSION: "2022"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "512G"
    devices:
      - /dev/vda3
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
