services:
  windows:
    image: dockurr/windows
    container_name: windows
    volumes:
      - /mnt/sdb:/data
    environment:
      VERSION: "win10"
      RAM_SIZE: "28G"
      CPU_CORES: "8"
      DISK_SIZE: "150G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
